# Generated by Django 3.1.2 on 2020-11-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
