# Generated by Django 3.1.2 on 2020-10-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20201012_1310'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('title', 'folder_parent'), name='unique_doc'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(fields=('title', 'user_owner'), name='unique_folder'),
        ),
    ]
