# Generated by Django 3.1.2 on 2020-11-01 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20201031_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='folder',
            name='last_access',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
