# Generated by Django 3.1.2 on 2020-11-05 11:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20201031_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='folder',
            name='last_access',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
